variables:
   ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase

withSmearing:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  
  script:
    - ls /cvmfs/atlas.cern.ch/
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - rcSetup Base,2.4.28
    - rc checkout_pkg atlasoff/PhysicsAnalysis/UpgradePhys/SmearingFunctions/UpgradePerformanceFunctions/tags
    - rc clean
    - rc find_packages
    - rc compile

withoutSmearing:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  
  script:
    - ls /cvmfs/atlas.cern.ch/
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    - rcSetup Base,2.4.28
    - rc clean
    - rc find_packages
    - rc compile
